# Generated by Django 4.2.16 on 2024-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeData', models.DateField(verbose_name='Data')),
                ('AgeHora', models.TimeField(verbose_name='Hora')),
                ('AgeInfo', models.CharField(max_length=100, verbose_name='indormação')),
                ('AgePrio', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baixa')], default='A', max_length=1, verbose_name='Prioridade')),
                ('AgeStat', models.CharField(choices=[('A', 'Aberto'), ('C', 'Concluido'), ('P', 'Pendente')], default='A', max_length=1, verbose_name='Status')),
            ],
        ),
    ]
