# Generated by Django 4.2.16 on 2024-11-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CultNome', models.CharField(help_text='Nome Cultura', max_length=20, verbose_name='Cultura')),
            ],
            options={
                'ordering': ['CultNome'],
            },
        ),
        migrations.CreateModel(
            name='ClEsporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EspNome', models.CharField(help_text='Nome esporte', max_length=20, verbose_name='Esport')),
            ],
            options={
                'ordering': ['EspNome'],
            },
        ),
        migrations.CreateModel(
            name='ClEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstNome', models.CharField(help_text='Nome Estudos', max_length=20, verbose_name='Estudos')),
            ],
            options={
                'ordering': ['EstNome'],
            },
        ),
        migrations.CreateModel(
            name='ClFesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FestNome', models.CharField(help_text='Nome Festa', max_length=20, verbose_name='Festa')),
            ],
            options={
                'ordering': ['FestNome'],
            },
        ),
        migrations.CreateModel(
            name='ClMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusNome', models.CharField(help_text='Nome Música', max_length=20, verbose_name='Musica')),
            ],
            options={
                'ordering': ['MusNome'],
            },
        ),
        migrations.CreateModel(
            name='ClCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cannome', models.CharField(help_text='Nome do candidato', max_length=50, verbose_name='Nome')),
                ('CultNome', models.ForeignKey(help_text='Cultura do candidato', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEnc.clcultura')),
                ('EspNome', models.ForeignKey(help_text='Esporte do candidato', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEnc.clesporte')),
                ('EstNome', models.ForeignKey(help_text='Estudos do candidato', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEnc.clestudo')),
                ('FestNome', models.ForeignKey(help_text='Festa do candidato', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEnc.clfesta')),
                ('MusNome', models.ForeignKey(help_text='Música do candidato', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppEnc.clmusica')),
            ],
        ),
    ]
